CREATE TABLE Admins (
    AdminID INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(50) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);
SELECT * FROM Admins;